---
title: "Exploratory Data Analysis Week 1 Project"
author: "Mike G"
date: "5/24/2020"
output: html_document
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
```

## Script setup and Data Import
```{r}
# import data file 
data_tbl<- read.table("household_power_consumption.txt",header = TRUE,na.strings = "?",sep = ";")


# format date column and filter data to dates of interest
data_tbl$Date<- as.Date(data_tbl$Date, format = "%d/%m/%Y")
data_subset<- subset(data_tbl,Date>= as.Date("2007-2-1") & Date<= as.Date("2007-2-2"))

#formate and create time vector
data_time<- paste(as.Date(data_subset$Date),data_subset$Time)
data_subset_time<- as.POSIXct(data_time)

```


## Plot 1: Global Active Power vs. Time
```{r}
png("plot1.png", height=480, width=480)
# Plot Number 1
hist(data_tbl$Global_active_power,col = "red", main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency")

dev.off()
```
## Plot 2: Voltage vs. Time

```{r }
#Plot Number 2
png("plot2.png", height=480, width=480)
plot(data_subset_time,data_subset$Global_active_power,type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")

dev.off()
```


##Plot Number 3
```{r}

#create labels for 3rd graph
png("plot3.png", height=480, width=480)
plot(data_subset_time,data_subset$Sub_metering_1,type = "l", col="black",xlab="",ylab= "Energy sub metering")
lines(data_subset_time,data_subset$Sub_metering_2,col = "red")
lines(data_subset_time,data_subset$Sub_metering_3,col = "blue")
col_lbls = c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright",legend= col_lbls,col = c("black","red","blue"),lty= "solid")
dev.off()
```

## Plot 4: Global Reactive Power vs. Time
```{r}
png("plot4.png", height=480, width=480)
#plot 4
par(mfrow = c(2,2))
plot(data_subset_time,data_subset$Global_active_power,type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
plot(data_subset_time,data_subset$Voltage,type = "l", ylab = "Voltage (volts)", xlab = "")
plot(data_subset_time,data_subset$Sub_metering_1,type = "l", col="black",xlab="",ylab= "Energy sub metering")
lines(data_subset_time,data_subset$Sub_metering_2,col = "red")
lines(data_subset_time,data_subset$Sub_metering_3,col = "blue")
col_lbls = c("Sub_metering_1","Sub_metering_2","Sub_metering_3")
legend("topright",legend= col_lbls,col = c("black","red","blue"),lty= "solid")
plot(data_subset_time,data_subset$Global_reactive_power,type = "l", ylab = "Global Active Power (kilowatts)", xlab = "")
dev.off()
```

